apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-org-monitor
  app.kubernetes.io/instance: fint-org-monitor_ofk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: ofk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/env/0/value"
        value: "api"
      - op: replace
        path: "/spec/env/2/value"
        value: "integrasjoner.elements@ofk.no"
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-org-monitor_ofk_no"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
    target:
      kind: Application
      name: fint-org-monitor

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-org-monitor-client_ofk_no"
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
    target:
      kind: FintClient
      name: fint-org-monitor-client