services:
  postgres:
    image: postgres:18
    container_name: org_mon_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  network-bridge:
    driver: bridge