apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viken-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-org-monitor
  app.kubernetes.io/instance: fint-org-monitor_viken_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: viken.no
patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-org-monitor_viken_no"
      - op: replace
        path: "/spec/orgId"
        value: "viken.no"
    target:
      kind: Application
      name: fint-org-monitor
