management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  profiles:
    include:
      - oauth
      - config
      - database

jakarta:
  validation:
    constraints:
      NotBlank:
        message: "Cannot be blank"