apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: org-monitor-viken
spec:
  itemPath: "vaults/aks-api-vault/items/org-monitor-viken"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: org-monitor-viken-no
  labels:
    name: org-monitor-viken-no
spec:
  selector:
    matchLabels:
      name: org-monitor-viken-no
  template:
    metadata:
      labels:
        name: org-monitor-viken-no
    spec:
      containers:
        - name: viken-no
          image: fintlabs.azurecr.io/fint-org-monitor:dummy
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: org-monitor-viken
          env:
            - {name: fint.orgmonitor.endpoint, value: 'https://api.felleskomponent.no/administrasjon/organisasjon/organisasjonselement'}
            - {name: fint.orgmonitor.application-name, value: 'FINT Organization Monitor for Viken Fylkeskommune'}
            - {name: fint.orgmonitor.orgid, value: 'viken.no'}
            - {name: fint.orgmonitor.recipients, value: 'henrik@fintlabs.no'}
            - {name: fint.orgmonitor.sender, value: 'henknut@outlook.com'}
            - {name: fint.orgmonitor.interval, value: '3600000'}
            - {name: spring.data.mongodb.uri, valueFrom: { secretKeyRef: { key: mongodb, name: fint-mongo}}}
            - {name: spring.data.mongodb.database, value: 'org-monitor-api'}
