apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: org-monitor-viken
spec:
  itemPath: "vaults/aks-api-vault/items/org-monitor-viken"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: org-monitor-viken-no
  labels:
    name: org-monitor-viken-no
  annotations:
    operator.1password.io/item-path: "vaults/aks-api-vault/items/org-monitor-viken"
    operator.1password.io/item-name: "org-monitor-viken"
spec:
  selector:
    matchLabels:
      name: org-monitor-viken-no
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "provider/actuator/prometheus"
      labels:
        name: org-monitor-viken-no
    spec:
      containers:
        - name: viken-no
          image: fintlabsacr.azurecr.io/fint-org-monitor:dummy
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: org-monitor-viken
          env:
            - { name: fint.orgmonitor.endpoint, value: 'https://api.felleskomponent.no/administrasjon/organisasjon/organisasjonselement' }
            - { name: fint.orgmonitor.application-name, value: 'FINT Organization Monitor for Viken Fylkeskommune' }
            - { name: fint.orgmonitor.orgid, value: 'viken.no' }
            - { name: fint.orgmonitor.sender, value: 'drift@vigoiks.no' }
            - { name: fint.orgmonitor.recipients, value: 'brukerhjelp@viken.no' }
            - { name: fint.orgmonitor.cron, value: '0 15 8-14/2 * * *' }
            - { name: spring.data.mongodb.uri, valueFrom: { secretKeyRef: { key: mongodb, name: fint-mongo-db } } }
            - { name: spring.data.mongodb.database, value: 'org-monitor-api' }
